# Copyright (C) 2019 - present Instructure, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: flutter_parent
description: Canvas Parent

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.4.0+42

module:
  androidX: true

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: 2.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^8.3.4
  firebase_remote_config: ^0.11.0+2
  firebase_core: ^1.8.0
  firebase_crashlytics: ^2.2.4
  get_it: 6.1.1
  intl: ^0.17.0
  provider: ^5.0.0
  vector_math: ^2.1.0
  tuple: ^2.0.0
  flutter_slidable: ^0.6.0
  percent_indicator: ^3.4.0
  sqflite: ^2.0.0+4
  faker: ^2.0.0
  uuid: ^3.0.5
  collection: ^1.15.0
  flutter_linkify: ^5.0.2
  email_validator: ^2.0.1

  # File handling
  path_provider: ^2.0.6
  flutter_downloader: ^1.7.1
  mime: ^1.0.1
  file_picker: ^4.2.0

  # Media handling
  flutter_svg: ^0.23.0+1
  image_picker: ^0.8.4+4
  transparent_image: ^2.0.0
  cached_network_image: ^3.1.0
  photo_view: ^0.13.0
  video_player: ^2.2.6
  chewie: ^1.2.2
  barcode_scan2: 4.1.4

  # Networking / Serialization
  dio: ^4.0.1
  dio_http_cache: ^0.3.0
  dio_smart_retry: ^1.0.3
  built_value: ^8.1.3
  built_collection: ^5.1.1

  # Platform interactions
  android_intent_plus: ^3.0.2
  device_info: ^2.0.3
  encrypted_shared_preferences: # Used by ApiPrefs to securely store data
    path: ./plugins/encrypted_shared_preferences
  flutter_local_notifications: ^9.0.2
  package_info: ^2.0.2
  permission_handler: ^8.2.5
  shared_preferences: ^2.0.8 # Used to cache remote config properties
  #webview_flutter: 0.3.19+5
  webview_flutter: # TODO: Remove once the flutter plugin supports baseUrl https://github.com/flutter/plugins/pull/2463
    path: ./plugins/webview_flutter

  # Routing
  fluro: ^2.0.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  intl_generator: ^0.2.0+0
  mockito: ^5.0.15

  build_resolvers: ^2.0.4
  build_runner: ^2.1.4
  built_value_generator: ^8.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/bottom-nav/
    - assets/png/
    - assets/fonts/
    - assets/html/html_wrapper.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family:  CanvasIcons
      fonts:
        - asset: assets/fonts/CanvasIcons.ttf
    - family:  CanvasIconsSolid
      fonts:
        - asset: assets/fonts/CanvasIconsSolid.ttf
    - family:  Lato
      fonts:
        - asset: assets/fonts/lato_regular.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
