# Copyright (C) 2019 - present Instructure, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: flutter_parent
description: Canvas Parent

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+24

module:
  androidX: true

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  flutter_crashlytics: ^1.0.0
  get_it: ^3.0.1
  intl: ^0.16.0
  package_info: 0.4.0+10
  provider: ^3.1.0+1
  shared_preferences: 0.5.3+4
  webview_flutter: 0.3.19+5
  device_info: 0.4.1+3
  vector_math: 2.0.8
  tuple: 1.0.3
  flutter_slidable: 0.5.4

  # Image handling
  flutter_svg: 0.14.3
  image_picker: 0.6.1+4
  file_picker: 1.4.2
  transparent_image: 1.0.0
  cached_network_image: 2.0.0-rc

  # Networking / Serialization
  dio: 3.0.5
  dio_http_cache: 0.2.5
  built_value: '>=5.5.5 <7.0.0'
  built_collection: 4.2.2

  url_launcher: 5.2.5

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  intl_translation: ^0.17.7
  mockito: 4.1.1

  build_runner: ^1.7.2
  built_value_generator: '>=5.5.5 <7.0.0'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/
    - assets/html/html_wrapper.html

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family:  CanvasIcons
      fonts:
        - asset: assets/fonts/CanvasIcons.ttf
    - family:  CanvasIconsSolid
      fonts:
        - asset: assets/fonts/CanvasIconsSolid.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
